# Generated by Django 4.2.6 on 2023-10-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoogleDisc',
            new_name='Site',
        ),
    ]
