# Generated by Django 4.2.6 on 2023-10-31 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0002_rename_googledisc_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='site',
            name='URL_link',
        ),
        migrations.RemoveField(
            model_name='site',
            name='name',
        ),
    ]
