# Generated by Django 4.2.6 on 2023-11-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0004_file_name_file_upload_photo_upload_site_url_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL_link', models.URLField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
